---
title: "ds202_lab2"
author: "Guang Yi Lim"
date: "February 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
choco <-read.csv("https://xdaiisu.github.io/ds202materials/hwlabs/choco.csv")
head(choco)

#q1 Individual
```{r}
  hist(choco$Rating)
  summary(choco$Rating)
  lowerq = quantile(choco$Rating)[2]
  upperq = quantile(choco$Rating)[4]
  iqr = upperq - lowerq
  length(which(choco$Rating < summary(choco$Rating)[["1st Qu."]]-1.5*iqr))
  length(which(choco$Rating > summary(choco$Rating)[["3rd Qu."]]+1.5*iqr))
```
The histogram is skewed towards the left. The mean is 3.191 while the median is 3.250. There are a total of 51 outliers, 49 lower outliers and 2 upper outliers. 

#q2 Individual
```{r}
  plot(choco$Cocoa.Pct,choco$Rating)
```
#Most chocolates had a cacao percentage of 70. However,chocolates with less than 50 cacao percentage never got a score less than 2, while chocolates with a 100 cacao percentage had more lower scores compared to the rest